// O'zbekcha tarjimalar. Kalit = data.js'dagi yozuv id'si.
// pairs: {q, a, n}  |  facts (term bor): {d}  |  facts (term yo'q): {t}
// Tarjimasi yo'q yozuvlar ruscha ko'rsatiladi (RU belgisi bilan).
const UZ = {};

// Перифразы p0–p59
Object.assign(UZ, {
  p0:{q:"Arxangelsklik mujik"}, p1:{q:"Rus aviatsiyasining otasi"},
  p2:{q:"Rus radiosining otasi"}, p3:{q:"Rus kosmonavtikasining otasi"},
  p4:{q:"Rus teatrining asoschisi"}, p5:{q:"Ballada qiroli"},
  p6:{q:"Vals qiroli"}, p7:{q:"Ertaklar qiroli"},
  p8:{q:"Buyuk kobzar"}, p9:{q:"Jahon proletariatining dohiysi"},
  p10:{q:"Barcha davrlar va xalqlar dohiysi"}, p11:{q:"Xalqlar otasi"},
  p12:{q:"Buyuk darg'a"}, p13:{q:"Inqilob bo'ronqushi"},
  p14:{q:"Inqilob jarchisi"}, p15:{q:"Go'zal xonim ritsari"},
  p16:{q:"Qizil graf"}, p17:{q:"Butunittifoq oqsoqoli"},
  p18:{q:"G'alaba marshali"}, p19:{q:"Kulrang kardinal"},
  p20:{q:"Don kazaklari kuychisi"}, p21:{q:"«Iliqlik davri»ning otasi"},
  p22:{q:"Koinot Kolumbi"}, p23:{q:"Qayta qurish arxitektori"},
  p24:{q:"Temir xonim"}, p25:{q:"Rus raketasi"},
  p26:{q:"To'q sariq malika"}, p27:{q:"Qo'shiq aytayotgan ayol"},
  p28:{q:"Rus she'riyati quyoshi"}, p29:{q:"Toj kiygan Gamlet"},
  p30:{q:"Rus inqilobining Iudushkasi"}, p31:{q:"Kreml xayolparasti"},
  p32:{q:"Rus inqilobining ko'zgusi"}, p33:{q:"Rus adabiyotining eng yuvosh shoiri"},
  p34:{q:"Rus tabiati kuychisi"}, p35:{q:"Sokin amerikalik",a:"CIA (Markaziy razvedka boshqarmasi) xodimi"},
  p36:{q:"O'lim farishtasi"}, p37:{q:"Oq xalatlilar",a:"Ku-kluks-klan a'zolari"},
  p38:{q:"Suv baleti",a:"Sinxron suzish"}, p39:{q:"Ikki qanotli bandit",a:"AQSh dollari"},
  p40:{q:"Muz jangi",a:"Xokkey o'yini"}, p41:{q:"Gudzon qirg'oqlarida",a:"Nyu-Yorkda"},
  p42:{q:"Potomak qirg'oqlarida",a:"Vashingtonda"},
  p43:{q:"Yashil beretlar",a:"Amerika diversiya qo'shinlari"},
  p44:{q:"Qizil beretlar",a:"Buyuk Britaniya armiyasi parashyutchilari"},
  p45:{q:"To'q sariq beretlar",a:"Rossiya FVV xodimlari"},
  p46:{q:"Qora beretlar",a:"Chilidagi dengiz desantchilari"},
  p47:{q:"Asr kasalligi",a:"Narkomaniya/OITS"},
  p48:{q:"San'atlarning eng muhimi",a:"Kino"},
  p49:{q:"Plash va xanjar (ritsarlari) idorasi",a:"CIA (Markaziy razvedka boshqarmasi)"},
  p50:{q:"Qora Venera"}, p51:{q:"Osiyo Venetsiyasi",a:"Bangkok"},
  p52:{q:"Amazonka Venetsiyasi",a:"Ikitos (Peruda)"},
  p53:{q:"To'rtinchi hokimiyat",a:"OAV"},
  p54:{q:"Raqs sehrgari"}, p55:{q:"Abadiy kechagilar",a:"Revanshistlar / hozirgi Rossiyadagi kommunistlar"},
  p56:{q:"Buyuk soqov",a:"Ovozsiz kino"},
  p57:{q:"Kakku uyasi",a:"Ruhiy kasalxona"},
  p58:{q:"Kremllik tog'lik"}, p59:{q:"Katta olma shahri",a:"Nyu-York"},
});

// Перифразы p60–p119
Object.assign(UZ, {
  p60:{q:"Birodarlik muhabbati shahri",a:"Filadelfiya"},
  p61:{q:"Shamollar shahri",a:"Chikago"},
  p62:{q:"Suv shahri",a:"Osaka"},
  p63:{q:"Xayrli shamollar shahri",a:"Buenos-Ayres"},
  p64:{q:"Qirollar shahri",a:"Krakov"},
  p65:{q:"Sher shahri",a:"Singapur"},
  p66:{q:"Ustalar shahri",a:"Tula"},
  p67:{q:"«Biznikilar» shahri",a:"Vladivostok"},
  p68:{q:"Sport shahri",a:"«Lujniki» sport majmuasi"},
  p69:{q:"Uch inqilob shahri",a:"Leningrad"},
  p70:{q:"Yoshlik shahri",a:"Komsomolsk-na-Amure"},
  p71:{q:"Kameliyali xonim",a:"Fohisha"},
  p72:{q:"Sahro daraxti",a:"Saksovul"},
  p73:{q:"Ertaklar uyi",a:"Soyuzmultfilm"},
  p74:{q:"«Bardoshlilik uyi»",a:"Fohishaxona"},
  p75:{q:"Adriatika marvaridi",a:"Venetsiya"},
  p76:{q:"Oq dengiz marvaridi",a:"Solovki orollari"},
  p77:{q:"Dunay marvaridi",a:"Budapesht"},
  p78:{q:"Ladoga marvaridi",a:"Valaam oroli"},
  p79:{q:"Tyan-Shan marvaridi",a:"Issiqko'l"},
  p80:{q:"Qora dengiz marvaridi",a:"Odessa"},
  p81:{q:"Femida kohini",a:"Yurist"},
  p82:{q:"Baxus ichimligi",a:"Alkogol"},
  p83:{q:"Gulliverlar o'yini",a:"Basketbol"},
  p84:{q:"Orzular imperiyasi",a:"Gollivud"},
  p85:{q:"XX asr inkvizitorlari",a:"Ku-kluks-klan a'zolari"},
  p86:{q:"Hosildorlik toshi",a:"Apatit"},
  p87:{q:"Abadiy tosh",a:"Granit"},
  p88:{q:"Yonuvchi tosh",a:"Slanets"},
  p89:{q:"Ko'k kaskalar",a:"BMT tinchlikparvar kuchlari"},
  p90:{q:"Mis kaskalar",a:"AQSh qurolli kuchlari"},
  p91:{q:"Quyoshli masxaraboz",a:"Oleg Popov"},
  p92:{q:"Qimorxonalar knyazligi",a:"Monako"},
  p93:{q:"Buyuk kombinator",a:"Ostap Bender"},
  p94:{q:"Muz komissari",a:"O.Yu. Shmidt"},
  p95:{q:"Yonayotgan qit'a",a:"Lotin Amerikasi"},
  p96:{q:"Hayot ildizi",a:"Jenshen"},
  p97:{q:"Quyosh ildizi",a:"Qizilmiya (lakritsa)"},
  p98:{q:"Kometalar malikasi",a:"Galley kometasi"},
  p99:{q:"Chang'i malikasi",a:"Lyubov Yegorova"},
  p100:{q:"Qalblar malikasi",a:"Malika Diana"},
  p101:{q:"Sport malikasi",a:"Yengil atletika"},
  p102:{q:"Jaz qiroli",a:"Bi Bi King"},
  p103:{q:"Cholg'ular qiroli",a:"Organ"},
  p104:{q:"Rok-n-roll qiroli",a:"Elvis Presli"},
  p105:{q:"Sport qiroli",a:"Futbol"},
  p106:{q:"Raqs qiroli",a:"Mahmud Esambayev"},
  p107:{q:"Futbol qiroli",a:"Pele"},
  p108:{q:"Epidemiyalar qiroli",a:"Gripp"},
  p109:{q:"Butunittifoq o'txonasi",a:"Donetsk ko'mir havzasi"},
  p110:{q:"Yangi butunittifoq o'txonasi",a:"Ekibastuz ko'mir havzasi"},
  p111:{q:"Mamlakatning ikkinchi o'txonasi",a:"Kuzbass"},
  p112:{q:"Uchinchi ko'mir o'txonasi",a:"Qarag'anda ko'mir havzasi"},
  p113:{q:"Ming ko'llar o'lkasi",a:"Kola yarim oroli"},
  p114:{q:"To'qimachilik o'lkasi",a:"Ivanovo viloyati"},
  p115:{q:"Sahro krevetkasi",a:"Chigirtka"},
  p116:{q:"Afrika tomi",a:"Lesoto"},
  p117:{q:"Qizil temirchixona",a:"Tula"},
  p118:{q:"Sayyora gumbazi",a:"Antarktida"},
  p119:{q:"Ob-havo oshxonasi",a:"Atlantika okeani"},
});

// Перифразы p120–p179
Object.assign(UZ, {
  p120:{q:"Qahrabo xonim",a:"Kazimera Prunskene"},
  p121:{q:"Lengli odamlari",a:"CIA xodimlari"},
  p122:{q:"Asr magistrali",a:"BAM (Baykal-Amur magistrali)"},
  p123:{q:"Yer cho'qqisi (tepasi)",a:"Arktika"},
  p124:{q:"Dunyo ustaxonasi",a:"Britaniya imperiyasi"},
  p125:{q:"Moda Makkasi",a:"Parij"},
  p126:{q:"Kalugalik xayolparast",a:"K.E. Tsiolkovskiy"},
  p127:{q:"Vengriya dengizi",a:"Balaton ko'li"},
  p128:{q:"Shahar dengizi",a:"Voronej suv ombori"},
  p129:{q:"Qirg'iz dengizi",a:"Issiqko'l"},
  p130:{q:"Rus baleti ilhomchisi",a:"G.S. Ulanova"},
  p131:{q:"Bolqon qassobi",a:"A. Artukovich"},
  p132:{q:"Lion qassobi",a:"K. Barbye"},
  p133:{q:"Osiyo Nyu-Yorki",a:"Singapur"},
  p134:{q:"Kastro oroli",a:"Kuba"},
  p135:{q:"Ziravorlar oroli",a:"Grenada"},
  p136:{q:"Zumrad (choy) oroli",a:"Shri-Lanka"},
  p137:{q:"Islohotlar otasi",a:"Yegor Gaydar"},
  p138:{q:"Rim otasi",a:"Tibr daryosi"},
  p139:{q:"Rus astronomiyasining otasi",a:"F.A. Bredixin"},
  p140:{q:"Tartu jallodi",a:"K. Linnas"},
  p141:{q:"Dengiz dehqoni",a:"Baliqchi"},
  p142:{q:"Arbat kuychisi",a:"Bulat Okudjava"},
  p143:{q:"Afrika chorrahasi",a:"Yuqori Volta (Burkina-Faso)"},
  p144:{q:"Yevropa chorrahasi",a:"Lyuksemburg"},
  p145:{q:"Safo muxlisasi",a:"Lesbiyanka"},
  p146:{q:"Uchinchi qutb",a:"Everest"},
  p147:{q:"Iroda saratoni",a:"Narkomaniya"},
  p148:{q:"Olmos respublikasi",a:"Yoqutiston"},
  p149:{q:"Uchinchi Rim",a:"Moskva"},
  p150:{q:"Budda vatani",a:"Nepal"},
  p151:{q:"Qora atirgul",a:"Qorako'l terisi"},
  p152:{q:"Arktika ritsari",a:"I.D. Papanin"},
  p153:{q:"Lamanchlik ritsar",a:"Don Kixot"},
  p154:{q:"Inqilob ritsari",a:"F.E. Dzerjinskiy"},
  p155:{q:"Melpomena xizmatkori",a:"Teatr aktyori"},
  p156:{q:"Panatseya xizmatkori",a:"Shifokor"},
  p157:{q:"Qadahdagi quyosh",a:"Vino"},
  p158:{q:"Antarktida poytaxti",a:"Molodyojnaya stansiyasi"},
  p159:{q:"BAM poytaxti",a:"Tinda shahri"},
  p160:{q:"Oq dengiz bo'yi poytaxti",a:"Arxangelsk"},
  p161:{q:"Gazchilar poytaxti",a:"Noviy Urengoy"},
  p162:{q:"Mafiya poytaxti",a:"Palermo"},
  p163:{q:"Dunyo poytaxti",a:"Nyu-York"},
  p164:{q:"Dengiz poytaxti",a:"Venetsiya"},
  p165:{q:"Qutb orti poytaxti",a:"Norilsk"},
  p166:{q:"Oq fil mamlakati",a:"Tailand"},
  p167:{q:"Vilgelm Tell mamlakati",a:"Shveytsariya"},
  p168:{q:"Vulqonlar mamlakati",a:"Indoneziya"},
  p169:{q:"Geyzerlar mamlakati",a:"Islandiya"},
  p170:{q:"Yovvoyi maymunlar mamlakati",a:"Braziliya"},
  p171:{q:"Zumradlar mamlakati",a:"Kolumbiya"},
  p172:{q:"Kedr mamlakati",a:"Livan"},
  p173:{q:"Burgutlar mamlakati",a:"Albaniya"},
  p174:{q:"Yetti ming orol mamlakati",a:"Filippin"},
  p175:{q:"Qor odam mamlakati",a:"Nepal"},
  p176:{q:"Ming suvlar mamlakati",a:"Gayana"},
  p177:{q:"Ming ko'llar mamlakati",a:"Finlyandiya"},
  p178:{q:"Tong tarovati mamlakati",a:"KXDR (Shimoliy Koreya)"},
  p179:{q:"Ikkinchi Transsib",a:"BAM"},
});

// Перифразы p180–p188, Прототипы p189–p212, Псевдонимы p213–p239
Object.assign(UZ, {
  p180:{q:"Ikkinchi non",a:"Kartoshka"},
  p181:{q:"Kapitoliy tepaligi",a:"AQSh Kongressi"},
  p182:{q:"Melpomena ibodatxonasi",a:"Teatr"},
  p183:{q:"Liverpul to'rtligi",a:"Bitlz"},
  p184:{q:"Amerika Shveytsariyasi",a:"Urugvay"},
  p185:{q:"Afrika Shveytsariyasi",a:"Svazilend (Esvatini)"},
  p186:{q:"Lotin Amerikasi Shveytsariyasi",a:"Kosta-Rika"},
  p187:{q:"O'n ming li devori",a:"Buyuk Xitoy devori"},
  p188:{q:"Yer shari raisi",a:"Velimir Xlebnikov"},
  p189:{q:"«Otello» personajining prototipi",n:"Yelizaveta I saroyidagi Marokash elchisi"},
  p190:{q:"«Rokki Balboa» personajining prototipi",n:"Amerikalik bokschi. Rokkining prototipi Rokki Marchiano (mag'lubiyatsiz amerikalik bokschi) degan noto'g'ri taxmin ham bor"},
  p191:{q:"«Gek Finn» personajining prototipi",n:"Mark Tvenning bolalikdagi do'sti"},
  p192:{q:"«Pyatachok (Cho'chqacha)» personajining prototipi",n:"Faqat Kristofer Robin emas ekan"},
  p193:{q:"«matros Lom» personajining prototipi",n:"«Kapitan Vrungel sarguzashtlari»dagi matros Lomning prototipi Ivan Mann (nem. Mann — odam — fr. l'homme) hisoblanadi. U 20-yillarda bilim yurtidagi o'rtoqlari bilan yaxtada dunyo aylanishga otlangan. Keyinchalik u haqiqatan ham «Tovarishch» barkida botsman sifatida dunyo bo'ylab suzgan, Shimolda va Antarktidada bo'lgan — xuddi qissa qahramonlari kabi."},
  p194:{q:"«olmaxon-kalamush Skret» personajining prototipi",n:"Uning toshqotgan qoldiqlari Ichki Mongoliyada topilgan."},
  p195:{q:"«Pavel Vereshchagin» personajining prototipi",n:"«Qizil shayton» laqabli Germab chegara otryadi qo'mondoni Mixail Pospelov"},
  p196:{q:"«Tom tog'a» personajining prototipi",n:"Amerikalik-kanadalik yozuvchi, abolitsionist va ruhoniy. Fuqarolik faoli."},
  p197:{q:"«Zolushka» personajining prototipi",a:"ma'buda Vesta",n:"O'choq ma'budasi, mushuk terisidan kiyim kiygan"},
  p198:{q:"«Betmen» personajining prototipi",a:"Sakrovchi Jek",n:"Viktoriya davri ingliz folklori personaji — hayratlanarli balandlikka sakray oladigan gumanoid mavjudot."},
  p199:{q:"«Midas» personajining prototipi",a:"shoh Mita",n:"Miloddan avvalgi VIII asrdagi proto-gruzin g'arbiy Mush davlati hukmdori"},
  p200:{q:"«Mayor» personajining prototipi",a:"Lenin",n:"Oruellning «Molxona» asari"},
  p201:{q:"«Napoleon» personajining prototipi",a:"Stalin",n:"Oruellning «Molxona» asari"},
  p202:{q:"«Snejok (Qorcha)» personajining prototipi",a:"Trotskiy",n:"Oruellning «Molxona» asari"},
  p203:{q:"«Vizgun (Chiyilloq)» personajining prototipi",a:"Molotov",n:"Oruellning «Molxona» asari"},
  p204:{q:"«Minimus» personajining prototipi",a:"Mayakovskiy/Mixalkov",n:"Oruellning «Molxona» asari"},
  p205:{q:"«Mister Jons» personajining prototipi",a:"Nikolay II/Kerenskiy",n:"Oruellning «Molxona» asari"},
  p206:{q:"«Mister Frederik» personajining prototipi",a:"Gitler",n:"Oruellning «Molxona» asari"},
  p207:{q:"«Mister Pilkington» personajining prototipi",a:"Uinston Cherchill",n:"Oruellning «Molxona» asari"},
  p208:{q:"«Mister Uimper» personajining prototipi",a:"Armand Xammer",n:"Oruellning «Molxona» asari"},
  p209:{q:"«Robinzon Kruzo» personajining prototipi",a:"Aleksandr Selkirk",n:"Shotland dengizchisi, sobiq qaroqchi — 4 yilu 4 oy (1704–1709) Mas-a-Tyerra kimsasiz orolida yashagan"},
  p210:{q:"«Chatskiy» personajining prototipi",a:"Chaadayev/Kyuxelbeker"},
  p211:{q:"«Fuqaro Keyn» personajining prototipi",a:"Uilyam Xyorst"},
  p212:{q:"«Komissar Kattani» personajining prototipi",a:"Nino Kassar",n:"«Sprut» serialidagi Palermo politsiyasi komissari"},
  p213:{n:"Yozuvchi Mark Tvenning asl ismi"},
  p214:{n:"Yozuvchi Lyuis Kerrollning asl ismi"},
  p215:{n:"Sovet grafik va rassomlarining ijodiy jamoasi. Guruh nomi ishtirokchilar familiyalarining bosh harflaridan tuzilgan: KUpriyanov+KRIlov+NIKolay Sokolov"},
  p216:{n:"To'rt yozuvchining jamoaviy taxallusi — u ostida ular XIX asrning 50-60-yillarida satirik she'rlar va aforizmlar chop etishgan"},
  p217:{n:"1935-yilda tuzilgan fransuz matematiklari guruhining jamoaviy taxallusi. Maqsad — o'sha davr matematikasi holatini aks ettiruvchi kitoblar turkumini yozish. Burbaki kitoblari qat'iy aksiomatik uslubda, Sermelo-Frenkel to'plamlar nazariyasi asosida yozilgan"},
  p218:{n:"Yozuvchi O.Genrining asl ismi"},
  p219:{n:"Yozuvchi Jek Londonning asl ismi"},
  p220:{n:"Kambodja diktatori Pol Potning asl ismi"},
  p221:{n:"Chexov taxalluslaridan biri"},
  p222:{n:"Chexov taxalluslaridan biri"}, p223:{n:"Chexov taxalluslaridan biri"},
  p224:{n:"Chexov taxalluslaridan biri"}, p225:{n:"Chexov taxalluslaridan biri"},
  p226:{n:"Chexov taxalluslaridan biri"}, p227:{n:"Chexov taxalluslaridan biri"},
  p228:{n:"Chexov taxalluslaridan biri"}, p229:{n:"Chexov taxalluslaridan biri"},
  p230:{n:"Chexov taxalluslaridan biri"}, p231:{n:"Chexov taxalluslaridan biri"},
  p232:{n:"Chexov taxalluslaridan biri"}, p233:{n:"Chexov taxalluslaridan biri"},
  p234:{n:"Chexov taxalluslaridan biri"}, p235:{n:"Chexov taxalluslaridan biri"},
  p236:{n:"Chexov taxalluslaridan biri"}, p237:{n:"Chexov taxalluslaridan biri"},
  p238:{n:"Chexov taxalluslaridan biri"}, p239:{n:"Chexov taxalluslaridan biri"},
});

// Псевдонимы p240–p287, Имена p288–p292, Олимпийские p293–p299
Object.assign(UZ, (function(){
  const o = {};
  for (let i = 240; i <= 282; i++) o['p'+i] = {n:"Chexov taxalluslaridan biri"};
  return o;
})());
Object.assign(UZ, {
  p283:{n:"Yozuvchi Ilya Ilfning asl ismi"},
  p284:{n:"Yozuvchi Yevgeniy Petrovning asl ismi"},
  p285:{n:"Faylasuf Volterning asl ismi"},
  p286:{n:"Serial qahramoni Shtirlitsning «asl» ismlari"},
  p287:{n:"Yozuvchi Andrey Platonovning asl familiyasi"},
  p288:{q:"«Iosif» ismining boshqa mamlakatlardagi muqobillari",a:"Jozef, Jozeff, Juzeppe, Yozef, Xose"},
  p289:{q:"«Yevgeniy» ismining boshqa mamlakatlardagi muqobillari",a:"Ejen, Yujin"},
  p290:{q:"«Ivan» ismining boshqa mamlakatlardagi muqobillari",a:"Jon, Jovanni, Yan, Xuan"},
  p291:{q:"«Anton» ismining boshqa mamlakatlardagi muqobillari",a:"Toni, Entoni, Antuan"},
  p292:{q:"«Georgiy» ismining boshqa mamlakatlardagi muqobillari",a:"Xorxe, Jorj, Gosha, Jorjo, Yurgen"},
  p293:{q:"1896-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Afina (Gretsiya)"},
  p294:{q:"1900-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Parij (Fransiya)"},
  p295:{q:"1904-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Chikago – Sent-Luis (AQSh)"},
  p296:{q:"1906-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Afina (Gretsiya)"},
  p297:{q:"1908-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Rim–London (Italiya–Buyuk Britaniya)"},
  p298:{q:"1912-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Stokgolm (Shvetsiya)"},
  p299:{q:"1916-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Berlin (Germaniya)"},
});

// Олимпийские p300–p351, Искусство p352–p359
Object.assign(UZ, {
  p300:{q:"1920-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Antverpen (Belgiya)"},
  p301:{q:"1924-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Parij (Fransiya)"},
  p302:{q:"1924-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Shamoni (Fransiya)"},
  p303:{q:"1928-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Amsterdam (Niderlandiya)"},
  p304:{q:"1928-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Sankt-Morits (Shveytsariya)"},
  p305:{q:"1932-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Los-Anjeles (AQSh)"},
  p306:{q:"1932-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Leyk-Plesid (AQSh)"},
  p307:{q:"1936-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Berlin (Germaniya)"},
  p308:{q:"1936-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Garmish-Partenkirxen (Bavariya, Germaniya)"},
  p309:{q:"1940-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Tokio – Xelsinki (Yaponiya – Finlyandiya)"},
  p310:{q:"1940-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Sapporo – Sankt-Morits – Garmish-Partenkirxen (Yaponiya – Shveytsariya – Germaniya)"},
  p311:{q:"1944-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"London (Buyuk Britaniya)"},
  p312:{q:"1944-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Kortina d'Ampetsso (Veneto, Italiya)"},
  p313:{q:"1948-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"London (Buyuk Britaniya)"},
  p314:{q:"1948-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Sankt-Morits (Shveytsariya)"},
  p315:{q:"1952-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Xelsinki (Finlyandiya)"},
  p316:{q:"1952-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Oslo (Norvegiya)"},
  p317:{q:"1956-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Melburn (Avstraliya)"},
  p318:{q:"1956-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Kortina d'Ampetsso (Veneto, Italiya)"},
  p319:{q:"1960-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Rim (Italiya)"},
  p320:{q:"1960-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Skvo-Velli (Kaliforniya, AQSh)"},
  p321:{q:"1964-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Tokio (Yaponiya)"},
  p322:{q:"1964-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Insbruk (Avstriya)"},
  p323:{q:"1968-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Mexiko (Meksika)"},
  p324:{q:"1968-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Grenobl (Fransiya)"},
  p325:{q:"1972-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Myunxen (GFR)"},
  p326:{q:"1972-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Sapporo (Yaponiya)"},
  p327:{q:"1976-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Monreal (Kanada)"},
  p328:{q:"1976-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Denver – Insbruk (AQSh – Avstriya)"},
  p329:{q:"1980-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Moskva (SSSR)"},
  p330:{q:"1980-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Leyk-Plesid (AQSh)"},
  p331:{q:"1984-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Los-Anjeles (AQSh)"},
  p332:{q:"1984-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Sarayevo (Yugoslaviya)"},
  p333:{q:"1988-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Seul (Janubiy Koreya)"},
  p334:{q:"1988-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Kalgari (Kanada)"},
  p335:{q:"1992-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Barselona (Ispaniya)",n:"Medal bo'yicha g'olib: Birlashgan jamoa"},
  p336:{q:"1992-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Albervil (Fransiya)"},
  p337:{q:"1994-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Lillehammer (Norvegiya)",n:"Medal bo'yicha g'olib: Rossiya. Birinchi marta qishki Olimpiada yozgisi bilan bir yilda o'tkazilmadi. Sobiq sovet respublikalari birinchi marta alohida jamoalar sifatida qatnashdi."},
  p338:{q:"1996-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Atlanta (AQSh)",n:"Medal bo'yicha g'olib: AQSh. Erik Rudolf Olimpiya shaharchasi yonida portlash uyushtirgan"},
  p339:{q:"1998-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Nagano (Yaponiya)",n:"Medal bo'yicha g'olib: Germaniya"},
  p340:{q:"2000-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Sidney (Avstraliya)",n:"Medal bo'yicha g'olib: AQSh. Birinchi marta dasturga triatlon, taekvondo va batutda sakrash kiritildi."},
  p341:{q:"2002-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Solt-Leyk-Siti (AQSh)",n:"Medal bo'yicha g'olib: Norvegiya"},
  p342:{q:"2004-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Afina (Gretsiya)",n:"Medal bo'yicha g'olib: AQSh"},
  p343:{q:"2006-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Turin (Italiya)",n:"Medal bo'yicha g'olib: Germaniya"},
  p344:{q:"2008-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Pekin (XXR)",n:"Medal bo'yicha g'olib: Xitoy"},
  p345:{q:"2010-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Vankuver (Kanada)",n:"Medal bo'yicha g'olib: Kanada"},
  p346:{q:"2012-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"London (Buyuk Britaniya)",n:"Medal bo'yicha g'olib: AQSh"},
  p347:{q:"2014-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Sochi (Rossiya)",n:"Medal bo'yicha g'olib: Rossiya. Rossiya terma jamoasining doping mojarosi"},
  p348:{q:"2016-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Rio-de-Janeyro (Braziliya)",n:"Medal bo'yicha g'olib: AQSh"},
  p349:{q:"2018-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Pxyonchxan (Janubiy Koreya)",n:"Medal bo'yicha g'olib: Norvegiya"},
  p350:{q:"2021-yilgi yozgi Olimpiya o'yinlari qayerda o'tgan?",a:"Tokio (Yaponiya)",n:"Medal bo'yicha g'olib: AQSh"},
  p351:{q:"2022-yilgi qishki Olimpiya o'yinlari qayerda o'tgan?",a:"Pekin (XXR)",n:"Medal bo'yicha g'olib: Norvegiya"},
  p352:{q:"«O'liklar oroli» asarining muallifi",a:"Arnold Byoklin",n:"Bu kartinaning so'nggi va eng mashhur varianti, 1901-yilda yaratilgan. Berlindagi Eski Milliy galereyada saqlanadi"},
  p353:{q:"«Telefon-Omar» asarining muallifi",a:"Salvador Dali va Eduard Jeyms",n:"Skulptura — Dalining texnikaga, odamlarni bir-biridan uzoqlashtiruvchi audiokommunikatsiya vositalariga sig'inishga qarshi noroziligini ifodalovchi parodiya va hazil. Dalining so'zlariga ko'ra, «telefon — yangiliklarni uzatish vositasi», «kelajakda esa omarlar telefonlar o'rnini egallaydi»."},
  p354:{q:"«Arturning Avalondagi so'nggi tushi» asarining muallifi",a:"Edvard Byorn-Jons",n:"Prerafaelit Edvard Byorn-Jonsning magnum opus'i."},
  p355:{q:"«Olimpiya» asarining muallifi",a:"Eduard Mane",n:"«Olimpiya» — 1863-yilda fransuz impressionisti Eduard Mane chizgan kartina. 1865-yilgi Parij salonida namoyish etilganda san'at tarixidagi eng katta janjallardan biriga sabab bo'lgan. Kartina Fransiya davlati mulki bo'lib, 1986-yildan beri Parijdagi Orse muzeyida namoyish etiladi."},
  p356:{q:"«Qizil otliqlar chopmoqda» asarining muallifi",a:"Kazimir Malevich"},
  p357:{q:"«Italiya peshini» asarining muallifi",a:"Bryullov"},
  p358:{q:"«Italiya tongi» asarining muallifi",a:"Bryullov"},
  p359:{q:"«Tungi qushlar» asarining muallifi",a:"Edvard Xopper",n:"Edvard Xopper — amerikalik rassom va gravyurachi, Amerika janr rangtasvirining vakili. Kundalik hayot manzaralari bilan mashhur, ulardan eng mashhuri — «Tungi qushlar» (1942). Xopper ijodi san'at olamiga va XX asr pop-madaniyatiga kuchli ta'sir ko'rsatgan."},
});

// Искусство p360, Нобелевские p361–p380, Латинские p381–p385
Object.assign(UZ, {
  p360:{q:"«Amerika gotikasi» asarining muallifi",a:"Grant Vud"},
  p361:{q:"Ivan Petrovich Pavlov Nobel mukofotini qachon va nima uchun olgan?",a:"Fiziologiya va tibbiyot, 1904 — hazm qilish fiziologiyasi bo'yicha ishlari uchun"},
  p362:{q:"Ilya Mechnikov Nobel mukofotini qachon va nima uchun olgan?",a:"Fiziologiya va tibbiyot, 1908 — immunitet bo'yicha asarlari uchun"},
  p363:{q:"Genrik Senkevich Nobel mukofotini qachon va nima uchun olgan?",a:"Adabiyot, 1905 — epos sohasidagi ulkan xizmatlari uchun",n:"Mukofot topshirilgan paytda Rossiya imperiyasi fuqarosi bo'lgan"},
  p364:{q:"Ivan Alekseyevich Bunin Nobel mukofotini qachon va nima uchun olgan?",a:"Adabiyot, 1933 — adabiy nasrda tipik rus xarakterini qayta yaratgan qat'iy badiiy iste'dodi uchun",n:"Mukofot topshirilgan paytda Rossiya fuqarosi emas edi"},
  p365:{q:"Nikolay Nikolayevich Semyonov Nobel mukofotini qachon va nima uchun olgan?",a:"Kimyo, 1956 — kimyoviy reaksiya mexanizmlari sohasidagi tadqiqotlari uchun"},
  p366:{q:"Boris Leonidovich Pasternak Nobel mukofotini qachon va nima uchun olgan?",a:"Adabiyot, 1958 — zamonaviy lirik she'riyatdagi yutuqlari hamda buyuk rus epik romani an'analarini davom ettirgani uchun"},
  p367:{q:"Pavel Cherenkov, Igor Tamm va Ilya Frank Nobel mukofotini qachon va nima uchun olishgan?",a:"Fizika, 1958 — Cherenkov effektini kashf etib, izohlab bergani uchun"},
  p368:{q:"Lev Davidovich Landau Nobel mukofotini qachon va nima uchun olgan?",a:"Fizika, 1962 — kondensatsiyalangan muhitlar, ayniqsa suyuq geliy bo'yicha kashshof tadqiqotlari uchun"},
  p369:{q:"Nikolay Basov va Aleksandr Proxorov Nobel mukofotini qachon va nima uchun olishgan?",a:"Fizika, 1964 — kvant elektronikasi sohasidagi fundamental ishlari uchun (lazer-mazer tamoyilidagi nurlatgich va kuchaytirgichlar yaratilishiga olib kelgan)"},
  p370:{q:"Mixail Aleksandrovich Sholoxov Nobel mukofotini qachon va nima uchun olgan?",a:"Adabiyot, 1965 — Rossiya uchun burilish davridagi Don kazaklari haqidagi eposining badiiy kuchi va yaxlitligi uchun"},
  p371:{q:"Aleksandr Isayevich Soljenitsin Nobel mukofotini qachon va nima uchun olgan?",a:"Adabiyot, 1970 — rus adabiyotining o'zgarmas an'analariga ergashgan ma'naviy kuchi uchun"},
  p372:{q:"Leonid Vitalyevich Kantorovich Nobel mukofotini qachon va nima uchun olgan?",a:"Iqtisod, 1975 — resurslarni optimal taqsimlash nazariyasiga qo'shgan hissasi uchun"},
  p373:{q:"Andrey Dmitriyevich Saxarov Nobel mukofotini qachon va nima uchun olgan?",a:"Tinchlik mukofoti, 1975 — odamlar o'rtasidagi tinchlikning asosiy tamoyillarini qo'rqmas himoya qilgani va hokimiyat suiiste'moli hamda inson qadr-qimmatini bostirishning har qanday shakllariga qarshi mardona kurashi uchun"},
  p374:{q:"Pyotr Leonidovich Kapitsa Nobel mukofotini qachon va nima uchun olgan?",a:"Fizika, 1978 — past haroratlar fizikasidagi fundamental tadqiqot va kashfiyotlari uchun"},
  p375:{q:"Iosif Aleksandrovich Brodskiy Nobel mukofotini qachon va nima uchun olgan?",a:"Adabiyot, 1987 — fikr tiniqligi va she'riy ehtiros bilan yo'g'rilgan keng qamrovli ijodi uchun",n:"Mukofot topshirilgan paytda Rossiya fuqarosi emas edi"},
  p376:{q:"Mixail Sergeyevich Gorbachyov Nobel mukofotini qachon va nima uchun olgan?",a:"Tinchlik mukofoti, 1990 — xalqaro hamjamiyat hayotining muhim qismiga aylangan tinchlik jarayonidagi yetakchi roli e'tirofi sifatida"},
  p377:{q:"Jores Ivanovich Alfyorov Nobel mukofotini qachon va nima uchun olgan?",a:"Fizika, 2000 — yarimo'tkazgich texnikasidagi ishlanmalari uchun"},
  p378:{q:"Aleksey Abrikosov va Vitaliy Ginzburg Nobel mukofotini qachon va nima uchun olishgan?",a:"Fizika, 2003 — ikkinchi tur o'ta o'tkazuvchanlik nazariyasi va geliy-3 o'ta oquvchanligi nazariyasini yaratganliklari uchun"},
  p379:{q:"Konstantin Sergeyevich Novosyolov Nobel mukofotini qachon va nima uchun olgan?",a:"Fizika, 2010 — ikki o'lchamli material grafenni tadqiq etish bo'yicha novatorlik tajribalari uchun"},
  p380:{q:"Dmitriy Andreyevich Muratov Nobel mukofotini qachon va nima uchun olgan?",a:"Tinchlik mukofoti, 2021 — demokratiya va mustahkam tinchlikning sharti bo'lgan so'z erkinligini himoya qilishdagi sa'y-harakatlari uchun"},
  p381:{a:"Mag'lublarga voy (holiga)",n:"Miloddan avvalgi 390-yilda Rimni egallagan gall sarkardasi Brennga nisbat beriladi"},
  p382:{a:"Atirgul ostida / Yashirincha",n:"Qadimgi rimliklar sukut ramzi sifatida atirgulni ziyofat paytida stol ustiga osib qo'yishgan — atirgul ostida (dasturxonda) aytilgan gaplar haqida hech qayerda gapirmaslik kerakligi belgisi sifatida."},
  p383:{a:"Mening aybim",n:"XI asrdan beri katoliklarning diniy marosimidagi tavba va iqror formulasi."},
  p384:{a:"Bu yerda ajdarlar yashaydi",n:"Klassik lotin iborasi Hic sunt leones («bu yerda sherlar bor»)ning qayta talqini — o'rta asr xaritalarida olamning chekkasidagi noma'lum yerlar shunday imzolangan."},
  p385:{a:"Xotira la'nati",n:"O'limdan keyingi jazo — jazolanuvchining hayoti haqidagi barcha guvohliklar o'chirib tashlangan."},
});
